# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='city',
            field=models.CharField(choices=[(b'del', b'Delhi NCR'), (b'gur', b'Gurgaon'), (b'mum', b'Mumbai'), (b'ban', b'Bangalore'), (b'hyd', b'Hyderabad'), (b'kol', b'Kolkata'), (b'pun', b'Pune'), (b'che', b'Chennai')], default=b'del', max_length=10),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='nearby_radius',
            field=models.BigIntegerField(default=20),
        ),
    ]
