# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('sluggedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SluggedModel')),
                ('description', models.TextField()),
                ('gigtime', models.DateTimeField()),
                ('gig_type', models.IntegerField(choices=[(1, b'House Gig'), (2, b'Public Gig')], default=1)),
                ('no_of_pax', models.IntegerField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=b'images/cover/')),
                ('video', models.FileField(blank=True, null=True, upload_to=b'video/cover')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('band_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('privacy', models.IntegerField(choices=[(1, b'Everyone'), (2, b'Friends'), (3, b'Friends of Friends')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, b'Inactive'), (1, b'Active')], default=1)),
                ('moderated', models.BooleanField(default=False)),
                ('artists', models.ManyToManyField(blank=True, to='accounts.Artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_gigs', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.sluggedmodel',),
        ),
        migrations.CreateModel(
            name='GigLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.GigLocation'),
        ),
        migrations.AddField(
            model_name='gig',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='went_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
