# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_giglocation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='gigtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gigs.GigLocation'),
        ),
    ]
